require('./asset/css/default.css')
require('./asset/css/font_awesome.css')
require('./asset/css/audio.css')
require('./asset/css/idangerous_swiper.css')
require('./index2.html')
var $ = require('./asset/js/jquery.min')
require('./asset/js/main')
require('./asset/js/ga')
require('./asset/js/jquery-ui-droppable-1.9.2')
require('./asset/js/jquery-tipsy-1.0')
require('./asset/js/jquery-ui-draggable-1.9.2')
require('./asset/js/jquery-scrollto-1.4.6.min')
require('./asset/js/audiojs')
require('./asset/js/jquery-queryloader-2.8.1')
require('./asset/js/jquery-parallax')
require('./asset/js/jquery-movescreen-1.0.min')
require('./asset/js/jquery-idangerous.swiper-2.4.1.min')
require('./asset/js/jquery-fullscreen-1.1.5.min')
require('./asset/js/jquery-easing-1.3.min')

